project_id = "xfcgunaxdlhopqlmqdzw"

[functions.bulk-upsert]
verify_jwt = false

[functions.fabric-lakehouse-sync]
verify_jwt = false

[functions.microsoft-graph]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.validate-material-request]
verify_jwt = false